apiVersion: v1
kind: Service
metadata:
  name: flask-tip-k8s-service
spec:
  selector:
    app: tip-app
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-tip-k8s
spec:
  selector:
    matchLabels:
      app: tip-app
  replicas: 2
  template:
    metadata:
      labels:
        app: tip-app
    spec:
      containers:
      - name: tip-app
        image: tip-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
